### ISSUE TITLE
java.lang.IllegalStateException: Missing required api key secret

### ISSUE THREAD

**Issue by siddhpuraamitr** [kitek/Aviary-Android-SDK#3]
On Android Studio I have imported module Aviary-SDK

also used meta data in AndroidMeniffest.xml

  
            

but many times I am getting below error

java.lang.IllegalStateException: Missing required api key secret
    at com.aviary.android.feather.cds.AviaryCdsService.onHandleIntent(AviaryCdsService.java:510)
    at com.aviary.android.feather.common.utils.os.AviaryIntentService$ServiceHandler.handleMessage(AviaryIntentService.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:211)
    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by mdtuyen** [comment]
I have same issue. When app closed, something as change wifi or when app running have a message crash but my app have no problem. Log file as you show
